### ISSUE TITLE
Carthage update failure 

### ISSUE THREAD

**Issue by kkkum** [IC2017/NearBY#1]
I'm using Xcode 8.3.3. When running the 'carthage update --platform iOS' command, I encountered the following build error:

`$ carthage update --platform iOS
*** Downloading ios-sdk.framework binary at "v0.10.0"
*** Skipped installing ios-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.0.1 and the local version is 3.1."
*** Checking out ios-sdk at "v0.10.0"
*** xcodebuild output can be found in /var/folders/x8/hsf3xrrx6cl75t_cby6g809w0000gn/T/carthage-xcodebuild.m97psa.log
*** Building scheme "AlchemyDataNewsV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "TradeoffAnalyticsV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "DialogV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "ToneAnalyzerV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "ConversationV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "RetrieveAndRankV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "VisualRecognitionV3" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "RestKit" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "RelationshipExtractionV1Beta" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "TextToSpeechV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "AlchemyLanguageV1" in WatsonDeveloperCloud.xcodeproj
*** Building scheme "SpeechToTextV1" in WatsonDeveloperCloud.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/xxx/Documents/xx/NearBY/NearBY/NearBY-iOS/Carthage/Checkouts/ios-sdk/WatsonDeveloperCloud.xcodeproj -scheme SpeechToTextV1 -configuration Release -derivedDataPath /Users/xxx/Library/Caches/org.carthage.CarthageKit/DerivedData/ios-sdk/v0.10.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/x8/hsf3xrrx6cl75t_cby6g809w0000gn/T/carthage-xcodebuild.m97psa.log`

**Comment by VidyasagarMSC** [comment]
@kkkum Can you try the code [here](https://github.com/VidyasagarMSC/NearBY)? This repo is up to date with Swift 3.1.
